[project]
name = "f1-notebooks"
version = "0.1.0"
description = "A collection of Jupyter notebooks for exploring and working with F1 data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastf1>=3.5.3",
    "jupyterlab>=4.4.0",
    "seaborn>=0.13.2",
]
